on: [push]

jobs:
  Tweet-Repo-Job:
    runs-on: ubuntu-latest
    name: A job to tweet my repository
    steps:
      - name: Tweet repo
        uses: obasekietinosa/tweet-for-code-review-action@v1.0
        with:
          api-key: ${{ secrets.TWITTER_API_KEY }}
          tweet-body: I just updated my repo. Check it out and let me know what you think
